---
version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          day: monday
          interval: weekly
      open-pull-requests-limit: 5
      labels:
          - dependencies
      commit-message:
          prefix: chore
