default_language_version:
  python: python3.14
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
  - id: check-yaml
    exclude: ^\.github/ISSUE_TEMPLATE/
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: detect-private-key
  - id: no-commit-to-branch
    args:
    - --branch
    - main
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.49.0
  hooks:
  - id: markdownlint
    args:
    - --fix
    stages:
    - manual
- repo: https://github.com/lovesegfault/beautysh
  rev: v6.4.3
  hooks:
  - id: beautysh
    args:
    - --indent-size
    - '4'
- repo: https://github.com/openstack/bashate
  rev: 2.1.1
  hooks:
  - id: bashate
    args:
    - --ignore=E006
    - E020
- repo: https://github.com/chrysa/pre-commit-tools
  rev: v0.1.1-95
  hooks:
  - id: makefile-check
  - id: yaml-sorter
    exclude: ^(\.github/|GitVersion\.yml)
  - id: json-sorter
  - id: env-file-check
  - id: adr-gate
  - id: regression-gate
    stages:
    - pre-push
  - id: env-example-sync
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.4.0
  hooks:
  - id: conventional-pre-commit
    stages:
    - commit-msg
    args:
    - feat
    - fix
    - docs
    - style
    - refactor
    - test
    - chore
    - perf
    - revert
    - ci
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.30.0
  hooks:
  - id: gitleaks
