sonar.projectKey=chrysa_github-actions
sonar.organization=chrysa
sonar.projectName=github-actions
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**
